FROM node:24

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends openssl && rm -rf /var/lib/apt/lists/*
RUN npm install -g pnpm@9

COPY package*.json ./
RUN npm install --legacy-peer-deps --include=dev --no-audit --no-fund

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev:all"]
